name: Release
on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

defaults:
    run:
        working-directory: apps/frontend

jobs:
    release:
        strategy:
            fail-fast: false
            matrix:
                platform: [windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: "./src-tauri -> target"

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Setup cache
              uses: actions/cache@v4
              with:
                  path: |
                    ~/.bun/install/cache
                    node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
                  restore-keys: |
                    ${{ runner.os }}-bun-

            - name: Install app dependencies
              run: bun install

            - name: Build app
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VITE_GA_TAG: "G-967XTGK665"
              with:
                  tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
                  releaseName: "DraftGap v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
                  releaseBody: "# Download DraftGap\n[Windows MSI](https://github.com/Tangent-90C/draftgap/releases/download/v__VERSION__/DraftGap___VERSION___x64_en-US.msi)\n[Windows Setup](https://github.com/Tangent-90C/draftgap/releases/download/v__VERSION__/DraftGap___VERSION___x64-setup.exe)"
                  projectPath: apps/frontend
                  tauriScript: bun x tauri
